....FF.FF..........F.F.........
======================================================================
FAIL: test_collatz_eval_i_equal_j_1 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 220, in test_collatz_eval_i_equal_j_1
    self.assertEqual(max_cycle_length,   7)
AssertionError: 20 != 7

======================================================================
FAIL: test_collatz_eval_i_equal_j_2 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 224, in test_collatz_eval_i_equal_j_2
    self.assertEqual(max_cycle_length,    17)
AssertionError: 118 != 17

======================================================================
FAIL: test_collatz_eval_i_larger_j_1 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 212, in test_collatz_eval_i_larger_j_1
    self.assertEqual(max_cycle_length, 20)
AssertionError: 0 != 20

======================================================================
FAIL: test_collatz_eval_i_larger_j_2 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 216, in test_collatz_eval_i_larger_j_2
    self.assertEqual(max_cycle_length,    174)
AssertionError: 0 != 174

======================================================================
FAIL: test_collatz_solve_2 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 318, in test_collatz_solve_2
    w.getvalue(), "42 59 113\n6 56 113\n3 5 8\n5 25 24\n")
AssertionError: '42 59 113\n6 56 113\n3 5 8\n5 25 21\n' != '42 59 113\n6 56 113\n3 5 8\n5 25 24\n'
  42 59 113
  6 56 113
  3 5 8
- 5 25 21
?       ^
+ 5 25 24
?       ^


======================================================================
FAIL: test_collatz_solve_4 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 332, in test_collatz_solve_4
    w.getvalue(), "60 52 113\n40 23 112\n40 40 9\n88 86 31\n")
AssertionError: '60 52 0\n40 23 0\n40 40 35\n88 86 0\n' != '60 52 113\n40 23 112\n40 40 9\n88 86 31\n'
- 60 52 0
?       ^
+ 60 52 113
?       ^^^
- 40 23 0
?       ^
+ 40 23 112
?       ^^^
- 40 40 35
?       ^^
+ 40 40 9
?       ^
- 88 86 0
?       ^
+ 88 86 31
?       ^^


----------------------------------------------------------------------
Ran 31 tests in 0.029s

FAILED (failures=6)
